on:
  push:
    branches:
    - master
  release:
    types:
    - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm install
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
      if: success() && startsWith( github.ref, 'refs/tags/releases/')
    - run: npm install
    - run: npm deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
  